sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_221252f11bb2_key -iv $encrypted_221252f11bb2_iv -in multi-production-k8s-53107666d0d5.json.enc -out multi-production-k8s-53107666d0d5.json -d
  - curl http://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
